apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-default
spec:
  limits:
  - type: Container
    max:
    cpu: "500m"
      memory: "1Gi"
    default:
      cpu: "100m"
      memory: "256Mi"
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
