apiVersion: v1
kind: LimitRange
metadata:
	name: demostest
spec:
	selector:
		matchLabels:
			run: demostest
	limits:
	- default:
		cpu: "500m"
		memory: "256Mi"
	defaultRequest:
		cpu: "200m"
		memory: "128Mi"
	type: Container