apiVersion: v1
kind: ClusterLimit
metadata:
  name: demostest
spec:
  selector:
    matchLabels:
      run: demostest
  limits:
  - type: Container
    default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
