apiVersion: v1
kind: Service
metadata:
  name: demostest
  labels:
    run: demostest
spec:
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 8888
  externalIPs:
    - 192.168.1.202
    - 192.168.0.197
  selector:
    run: demostest
  type: LoadBalancer
